### PR TITLE
Pass 404 response gracefully

### PR DESCRIPTION
**Pull request by bnf**
Call next() to invoke the applications 404 handler instead of
sending a 400 error to the client.

### CODE REVIEW

**Comment by kapouer** [comment]
I suppose it should be `statusCode >= 400`

**Comment by kapouer** [comment]
Do you want to fix it yourself so i can just accept the PR ?

**Comment by bnf** [comment]
Well, I'm not sure whether mapping all >=400 codes to 404 is always wanted.
I'd rather have 500 passed as 500. But I'd see that as next step.

So I'll push a fix.

**Comment by kapouer** [comment]
Maybe the error itself should be passed like `next(res.statusCode)`.
The domains and that change call for a major version bump, so i don't care if it breaks compat.

**Comment by bnf** [comment]
Hm.. I think it should be something like:
````
if (response.statusCode >= 400) {
	request.abort();
	if (response.statusCode == 404) {
		return next();
	}
	var err = new Error(response.statusMessage);
	err.status = response.statusCode;
	return next(err);
}
````
To create a proper Error as expected by something like https://www.npmjs.com/package/express-error-handler or described here: http://webapplog.com/error-handling-and-running-an-express-js-app/
But call next() without an error parameter for 404 as special case in order to allow other handlers (/the default 404 handler) to be invoked.

**Comment by kapouer** [comment]
Since this module has no test suite, it will have to wait a little before i publish it (i'll do some in-situ tests soon).

**Pull request merged**
